# Build on push and PR events
on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: "actions/checkout@v2"

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: build/outputs/apk/debug/*.apk
